name: nyt_analytics

profile: nyt_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  nyt_analytics:
    +schema: raw

models:
  nyt_analytics:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true